language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t popluharp/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true popluharp/docker-react npm run test
